ABILITY_NAMES = {
    "cs": {
        "double": "Dvojnásobník",
        "fast_points": "Fast Points",
        "boost": "10% Boost",
        "sabotage": "Sabotáž",
        "steal": "Krádež",
        "eraser": "Zmizík",
        "mirror_shield": "Zrcadlový štít",
        "insurance": "Pojistka",
    },
    "en": {
        "double": "Doubler",
        "fast_points": "Fast Points",
        "boost": "10% Boost",
        "sabotage": "Sabotage",
        "steal": "Steal",
        "eraser": "Eraser",
        "mirror_shield": "Mirror Shield",
        "insurance": "Insurance",
    },
    "he": {
        "double": "מכפיל",
        "fast_points": "נקודות מהירות",
        "boost": "בוסט 10%",
        "sabotage": "חבלה",
        "steal": "גניבה",
        "eraser": "מוחק",
        "mirror_shield": "מגן מראה",
        "insurance": "ביטוח",
    },
}
