STRINGS = {
    "cs": {
        # hlavní menu
        "app_title": "FARKLE se SCHOPNOSTMI KAŽDÝCH 5 TAHŮ",
        "brand": "FARKLE",
        "menu_tagline": "Kostky, riziko a schopnosti, které dokážou hru otočit.",
        "menu_rules_short": "1 = 100 · 5 = 50 · 3 stejné = 300+ · nová schopnost každých 5 tahů",
        "menu_goal": "Cíl: {target} bodů",
        "btn_start": "ZAČÍT HRU",
        "btn_settings": "NASTAVENÍ",

        # zadání jmen
        "win_title_p1": "Hráč 1",
        "win_title_p2": "Hráč 2",
        "label_name1": "JMÉNO HRÁČE 1",
        "label_name2": "JMÉNO HRÁČE 2",
        "btn_continue": "POKRAČOVAT",
        "btn_start_game": "START HRY",
        "err_title": "Chyba",
        "err_no_name": "Zadejte jméno!",
        "err_dup_name": "Zadejte jiný název!",

        # nastavení
        "settings_title": "NASTAVENÍ",
        "settings_target": "Cílové skóre",
        "settings_bank_min": "Minimální bank",
        "settings_resolution": "Rozlišení okna",
        "settings_language": "Jazyk",
        "btn_save": "ULOŽIT",
        "btn_back": "ZPĚT",
        "err_invalid_number": "Zadej platné kladné číslo!",
        "lang_cs": "ČEŠTINA",
        "lang_en": "ENGLISH",

        # herní obrazovka
        "game_window_suffix": "Farkle se SCHOPNOSTMI",
        "ability_prefix": "SCHOPNOST: ",
        "ability_used_suffix": " (POUŽITO)",
        "turn_label": "TAH #{turn}",
        "ledger_selected": "VYBRÁNO K ODLOŽENÍ",
        "ledger_round": "NASBÍRÁNO V KOLE",
        "points_suffix": "bodů",
        "die_kept": "ULOŽENO",
        "die_selected": "VYBRÁNO",
        "die_active": "AKTIVNÍ",
        "farkle_banner": "FARKLE! Tyhle kostky nic nebodují.",
        "btn_roll": "HÁZEJ",
        "btn_confirm": "POTVRĎ VÝBĚR",
        "btn_bank": "BANK",
        "log_empty": "Hra začíná...",

        # obrazovka výsledků
        "end_winner": "VÍTĚZ: {name}",
        "end_final_score": "Finální skóre",
        "end_turns": "Počet tahů",
        "end_farkles": "Farklů",
        "end_banks": "Úspěšných banků",
        "end_best_bank": "Nejvyšší bank",
        "end_total_banked": "Celkem vsazeno",
        "end_gained": "Získáno schopnostmi",
        "end_lost": "Ztraceno útoky",
        "end_abilities": "Použité schopnosti",
        "end_close": "ZAVŘÍT HRU",
        "no_abilities": "—",

        # herní hlášky (log)
        "ev_game_start": "Začíná hráč: {player}",
        "ev_primary_abilities": "Primární schopnosti — {p1}: {a1}, {p2}: {a2}",
        "ev_target": "Cíl: {target} bodů.",
        "ev_new_ability": "Nová schopnost pro {player}: {ability} (tah #{turn})",
        "ev_eraser": "Zmizík! {player} vymazal {opponent} posledních {penalty} bodů!",
        "ev_shield": "Zrcadlový štít! {opponent} má štít, útok se odrazil a stál {player} {penalty} bodů!",
        "ev_sabotage": "Sabotáž! {player} ubral soupeři {opponent} polovinu bodů (-{penalty} b)!",
        "ev_steal": "Krádež! {player} ukradl {opponent} 30 % bodů (+{amount} b)!",
        "ev_confirm_first": "⚠ Nejdřív potvrď výběr kostek!",
        "ev_insurance_saved": "Pojistka aktivována! Farkle, ale {player} si nechává {points} bodů.",
        "ev_insurance_failed": "Farkle! Pojistku {player} nezachránila, žádné body v kole.",
        "ev_farkle": "FARKLE! {player} ztrácí vše.",
        "ev_hot_dice": "Horké kostky! Házíš znovu všemi šesti!",
        "ev_banked": "{player} uložil {amount} bodů do banku.",

        # kombinace v bodovacím ledgeru
        "combo_six_kind": "6 stejných: {points}",
        "combo_straight": "Postupka: {points}",
        "combo_three_pairs": "3x dvojice: {points}",
        "combo_triple": "3x {value}: {points}",
    },
    "en": {
        "app_title": "FARKLE WITH ABILITIES EVERY 5 TURNS",
        "brand": "FARKLE",
        "menu_tagline": "Dice, risk, and abilities that can flip the game.",
        "menu_rules_short": "1 = 100 · 5 = 50 · 3 of a kind = 300+ · new ability every 5 turns",
        "menu_goal": "Goal: {target} points",
        "btn_start": "START GAME",
        "btn_settings": "SETTINGS",

        "win_title_p1": "Player 1",
        "win_title_p2": "Player 2",
        "label_name1": "PLAYER 1 NAME",
        "label_name2": "PLAYER 2 NAME",
        "btn_continue": "CONTINUE",
        "btn_start_game": "START GAME",
        "err_title": "Error",
        "err_no_name": "Please enter a name!",
        "err_dup_name": "Please enter a different name!",

        "settings_title": "SETTINGS",
        "settings_target": "Target score",
        "settings_bank_min": "Minimum bank",
        "settings_resolution": "Window resolution",
        "settings_language": "Language",
        "btn_save": "SAVE",
        "btn_back": "BACK",
        "err_invalid_number": "Enter a valid positive number!",
        "lang_cs": "ČEŠTINA",
        "lang_en": "ENGLISH",

        "game_window_suffix": "Farkle with Abilities",
        "ability_prefix": "ABILITY: ",
        "ability_used_suffix": " (USED)",
        "turn_label": "TURN #{turn}",
        "ledger_selected": "SELECTED TO BANK",
        "ledger_round": "COLLECTED THIS ROUND",
        "points_suffix": "points",
        "die_kept": "BANKED",
        "die_selected": "SELECTED",
        "die_active": "ACTIVE",
        "farkle_banner": "FARKLE! These dice don't score.",
        "btn_roll": "ROLL",
        "btn_confirm": "CONFIRM SELECTION",
        "btn_bank": "BANK",
        "log_empty": "The game begins...",

        "end_winner": "WINNER: {name}",
        "end_final_score": "Final score",
        "end_turns": "Turns played",
        "end_farkles": "Farkles",
        "end_banks": "Successful banks",
        "end_best_bank": "Best single bank",
        "end_total_banked": "Total banked",
        "end_gained": "Gained from abilities",
        "end_lost": "Lost to attacks",
        "end_abilities": "Abilities used",
        "end_close": "CLOSE GAME",
        "no_abilities": "—",

        "ev_game_start": "Starting player: {player}",
        "ev_primary_abilities": "Primary abilities — {p1}: {a1}, {p2}: {a2}",
        "ev_target": "Goal: {target} points.",
        "ev_new_ability": "New ability for {player}: {ability} (turn #{turn})",
        "ev_eraser": "Eraser! {player} wiped {opponent}'s last {penalty} points!",
        "ev_shield": "Mirror shield! {opponent} blocked the attack, costing {player} {penalty} points!",
        "ev_sabotage": "Sabotage! {player} cut {opponent}'s bank in half (-{penalty} pts)!",
        "ev_steal": "Steal! {player} stole 30% of {opponent}'s points (+{amount} pts)!",
        "ev_confirm_first": "⚠ Confirm your dice selection first!",
        "ev_insurance_saved": "Insurance activated! Farkle, but {player} keeps {points} points.",
        "ev_insurance_failed": "Farkle! Insurance couldn't save {player} — no points this round.",
        "ev_farkle": "FARKLE! {player} loses everything.",
        "ev_hot_dice": "Hot dice! Roll all six again!",
        "ev_banked": "{player} banked {amount} points.",

        "combo_six_kind": "Six of a kind: {points}",
        "combo_straight": "Straight: {points}",
        "combo_three_pairs": "Three pairs: {points}",
        "combo_triple": "Triple {value}s: {points}",
    },
}
